### ISSUE TITLE
Warning: Undefined variable $dependency in Scan/ClassInspector.php

### ISSUE THREAD

**Issue by MagePsycho** [yireo/Yireo_ExtensionChecker#20]
I tried to use this extension checker on Magento 2.4.4 as:
```
bin/magento yireo_extensionchecker:scan --module Vendor_Module
```
But it's giving me this error:
> Warning: Undefined variable $dependency in /var/www/html/vendor/yireo/magento2-extensionchecker/Scan/ClassInspector.php on line 112  

Is this extension not compatible with 2.4.4?

**Comment by jissereitsma** [comment]
I've been using this extension under PHP 8.1 and Magento 2.4.4 ever since that release came out. The composer file is reviewed properly to allow for Magento upgrades. So yes, it is compatible.

Instead, let's review the problem. This sounds like a typo to me which is now fixed: https://github.com/yireo/Yireo_ExtensionChecker/commit/bd15a4ee52810ab6d43e8fb14a145be73fad98d1
