### ISSUE TITLE
Usage of constant leads to requirement in composer.json, but not in module.xml

### ISSUE THREAD

**Issue by norgeindian** [yireo/Yireo_ExtensionChecker#32]
I'm not quite sure, if that's actually an issue or a module dependency would not be needed in this case. That's why I would like to bring it up for discussion.

In one of our modules, I'm using a constant from the Magento User module (`\Magento\User\Block\Role\Tab\Info::IDENTITY_VERIFICATION_PASSWORD_FIELD`)

Checking this module with the newest version of the extension checker, gives me the information, that the module is missing as composer dependency.
Nevertheless, it's not added in the `module.xml` file and the check does not require this.
 @jissereitsma , what's your opinion regarding this? In my understanding, a module dependency should also be needed to be able to use this constant, right?

**Comment by jissereitsma** [comment]
First of all, whenever a "component" is detected (either a Magento module, a Magento theme, or a library) it should pick up on both the module-name and the composer-name (because they are simply just two parts of the same component). I don't understand why that's not the case here yet. Let me look into this.

**Comment by jissereitsma** [comment]
By the way, I'm able to duplicate the issue.

**Comment by jissereitsma** [comment]
Haha, found it: `break` should be `continue`: https://github.com/yireo/Yireo_ExtensionChecker/commit/7cc1caad12e6215f76346c4b4370a3719d626306
